[package]
name = "parquet-maria"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rc-u8-reader = "2.0.16"
thrift = "0.17.0"
thrift_codec = "0.2.0"
